---

#- name: copy docker package
#  copy: src=docker-1:1.8.2-1-x86_64.pkg.tar.xz dest=/tmp/docker.pkg.tar.xz

#- name: install docker
#  pacman: name=/tmp/docker.pkg.tar.xz state=present

#- name: remove docker package
#  command: rm /tmp/docker.pkg.tar.xz

- name: install docker
  pacman: name=docker state=present

- name: load overlay module
  command: modprobe overlay

- name: create docker drop-in folder
  file: dest=/etc/systemd/system/docker.service.d state=directory

- name: add docker.service command override
  copy: src=00-docker-command.conf dest=/etc/systemd/system/docker.service.d/00-docker-command.conf

- name: add docker prune service
  copy: src=docker-prune.service dest=/etc/systemd/system/docker-prune.service

- name: add docker prune timer
  copy: src=docker-prune.timer dest=/etc/systemd/system/docker-prune.timer

- name: enable and start docker
  service: name=docker enabled=yes state=started

- name: enable and start the timer
  service: name=docker-prune.timer enabled=yes state=started

- name: copy consul config
  copy: src=docker.json dest=/etc/consul/consul.d/client/docker.json
  notify:
    - reload consul@client
    - reload consul@server

- name: touch /etc/environment.flannel
  file:
    dest="/etc/environment.flannel"
    state="touch"
