---

  - name: copy consul from s3
    s3:
      bucket="{{ lookup('env', 'IDENTIFIER') }}-{{ lookup('env', 'REGION') }}-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      mode="get"
      dest="/tmp/consul.pkg.tar.xz"
      object="/consul-0.7.0.1-x86_64.pkg.tar.xz"

  - name: install consul
    command: pacman --noconfirm -U /tmp/consul.pkg.tar.xz

  - name: create consul user
    user:
      name="consul"
      createhome="no"
      shell="/usr/bin/zsh"
      home="/etc/consul"

  - name: create consul directories
    file:
      dest="{{ item }}"
      state="directory"
      mode="0770"
      owner="consul"
      group="consul"
    with_items:
      - /etc/consul/consul.d
      - /etc/consul/consul.d/client
      - /etc/consul/consul.d/server
      - /etc/consul/consul.d/bootstrap
      - /etc/consul/ui
      - /run/consul
      - /var/consul

  - name: copy consul@.service
    copy:
      dest="/etc/systemd/system/consul@.service"
      src="consul@.service"
