---

  - name: copy consul from s3
    s3:
      bucket="{{ lookup('env', 'IDENTIFIER') }}-{{ lookup('env', 'REGION') }}-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      object="/consul-{{ package_version }}-x86_64.pkg.tar.xz"
      dest="/tmp/consul.pkg.tar.xz"
      mode="get"

  - name: install consul
    command: pacman --noconfirm -U /tmp/consul.pkg.tar.xz

  - name: create consul user
    user:
      name="consul"
      createhome="no"
      shell="/usr/bin/zsh"
      home="/etc/consul"

  - name: create consul directories
    file:
      dest="{{ item }}"
      state="directory"
      mode="0770"
      owner="consul"
      group="consul"
    with_items:
      - /etc/consul
      - /etc/consul/agent
      - /etc/consul/ui

  - name: copy check_mem
    copy:
      src="check_mem"
      dest="/usr/local/bin/check_mem"
      mode="755"

  - name: copy consul memory check definition
    copy:
      src="memory.check.json"
      dest="/etc/consul/agent/memory.check.json"
    notify:
      - reload consul

  - name: copy consul disk check definition
    copy:
      src="disk.check.json"
      dest="/etc/consul/agent/disk.check.json"
    notify:
      - reload consul

  - name: copy consul load check defininiot
    copy:
      src="load.check.json"
      dest="/etc/consul/agent/load.check.json"
    notify:
      - reload consul

  - name: template config.json
    template:
      src="config.json.tpl"
      dest="/etc/consul/agent/config.json"
    notify:
      - reload consul

  - name: template consul.service
    template:
      src="consul.service.tpl"
      dest="/etc/systemd/system/consul.service"
    notify:
      - daemon-reload
      - enable consul
      - start consul
