---

  - name: install polkit
    shell: |
      pacman --noconfirm -S polkit
      systemctl enable --now polkit

  - name: copy fleet from s3
    s3:
      bucket="us-west-2-development-archlinux-repository"
      mode="get"
      dest="/tmp/fleet.pkg.tar.xz"
      object="/fleet-v0.11.7-1-any.pkg.tar.xz"

  - name: install fleet
    command: pacman --noconfirm -U /tmp/fleet.pkg.tar.xz

  - name: create fleet user
    user:
      name="fleet"

  - name: copy id_rsa
    copy:
      src="{{ item }}"
      dest="/home/fleet/.ssh/{{ item }}"
      owner="fleet"
      group="fleet"
      mode="0600"
    items:
      - id_rsa
      - id_rsa.pub

  - name: authorize fleet user ssh key
    shell: |
      cat /home/fleet/.ssh/id_rsa.pub > /home/fleet/.ssh/authorized_keys
      chown fleet:fleet /home/fleet/.ssh/authorized_keys
      chmod 0600 /home/fleet/.ssh/authorized_keys

  - name: copy ssh.rc
    copy:
      src="ssh.rc"
      dest="/home/fleet/.ssh/rc"
      owner="fleet"
      group="fleet"
      mode="0600"

  - name: copy ssh.config
    copy:
      src="ssh.config"
      dest="/home/fleet/.ssh/config"
      owner="fleet"
      group="fleet"
      mode="0600"

  - name: create /etc/fleet permissions
    file:
      state="directory"
      dest="/etc/fleet"
      owner="fleet"
      group="fleet"
      mode="0770"

  - name: template /etc/fleet/fleet.conf
    template:
      src="fleet.conf.tpl"
      dest="/etc/fleet/fleet.conf"
      owner="fleet"
      group="fleet"
      mode="0660"
    notify:
      - restart fleet

  - name: create /usr/share/polkit-1/rules.d
    file:
      state="directory"
      dest="/usr/share/polkit-1/rules.d"

  - name: copy fleet polkit rules
    file:
      state="file"
      src="98-fleet-org.freedesktop.systemd1.rules"
      dest="/usr/share/polkit-1/rules.d/98-fleet-org.freedesktop.systemd1.rules"

  - name: copy fleet systemd files
    copy:
      src="fleet.{{ item }}"
      dest="/etc/systemd/system/fleet.{{ item }}"
    items:
      - socket
      - service
    notify:
      - daemon-reload
      - restart fleet

  - name: start fleet service
    command: systemctl enable --now fleet
