---

  - name: copy fleet from s3
    s3:
      bucket="us-west-2-development-archlinux-repository"
      mode="get"
      dest="/tmp/fleet.pkg.tar.xz"
      object="/fleet-v0.11.7-1-any.pkg.tar.xz"

  - name: install fleet
    command: pacman --noconfirm -U /tmp/fleet.pkg.tar.xz

  - name: create /etc/fleet
    file:
      state="directory"
      dest="/etc/fleet"

  - name: template /etc/fleet/fleet.conf
    template:
      src="fleet.conf.tpl"
      dest="/etc/fleet/fleet.conf"

  - name: copy fleet systemd files
    copy:
      src="fleet.{{ item }}"
      dest="/etc/systemd/system/fleet.{{ item }}"
    items:
      - socket
      - service
    notify:
      - daemon-reload
      - restart fleet

  - name: start fleet service
    command: systemctl enable --now fleet
