---

  - name: copy fleet from s3
    s3:
      bucket="us-west-2-development-archlinux-repository"
      mode="get"
      dest="/tmp/fleet.pkg.tar.xz"
      object="/fleet-v0.11.7-1-any.pkg.tar.xz"

  - name: install fleet
    command: pacman --noconfirm -U /tmp/fleet.pkg.tar.xz

  - name: create fleet user
    user:
      name="fleet"
      generate_ssh_key="yes"
      ssh_key_type="rsa"
      ssh_key_bits="2048"

  - name: authorize fleet user ssh key
    shell: >
      cat /home/fleet/.ssh/id_rsa.pub >> /home/fleet/.ssh/authorized_keys
      chown fleet:fleet /home/fleet/.ssh/authorized_keys
      chmod 0660 /home/fleet/.ssh/authorized_keys

  - name: create /etc/fleet permissions
    file:
      state="directory"
      dest="/etc/fleet"
      owner="fleet"
      group="fleet"
      mode="0770"

  - name: template /etc/fleet/fleet.conf
    template:
      src="fleet.conf.tpl"
      dest="/etc/fleet/fleet.conf"
      owner="fleet"
      group="fleet"
      mode="0660"
    notify:
      - restart fleet

  - name: copy fleet systemd files
    copy:
      src="fleet.{{ item }}"
      dest="/etc/systemd/system/fleet.{{ item }}"
    items:
      - socket
      - service
    notify:
      - daemon-reload
      - restart fleet

  - name: start fleet service
    command: systemctl enable --now fleet
