---

  - name: template docker-registry service
    template:
      src="docker-registry.service.tpl"
      dest="/etc/systemd/system/docker-registry.service"
      mode="0600"
    notify:
      - daemon-reload
    ignore_errors: yes

  - name: copy consul config
    copy:
      src="docker-registry.service.json"
      dest="/etc/consul/agent/docker-registry.service.json"
    notify:
      - reload consul

  - name: enable docker-registry
    service:
      name="docker-registry"
      enabled="yes"
      state="started"
