---

  - name: get ec2 facts
    action: ec2_facts

  - name: list tags on an instance
    ec2_tag:
      region: "{{ ansible_ec2_placement_region }}"
      resource: "{{ ansible_ec2_instance_id }}"
      state: list
    register: ec2_tags

  - name: touch /etc/environment.tags
    file:
      path: /etc/environment.tags
      mode: 0755
      state: touch

  - name: populate /etc/environment.tags
    lineinfile:
      dest: /etc/environment.tags
      regexp: '^{{ item.key | upper }}=.*'
      line: '{{ item.key | upper }}={{ item.value }}'
    with_dict: "{{ ec2_tags.tags }}"
