---

  - name: get ec2 facts
    action: ec2_facts

  - name: list tags on an instance
    ec2_tag:
      region: "{{ ansible_ec2_placement_region }}"
      resource: "{{ ansible_ec2_instance_id }}"
      state: list
    register: ec2_tags

  - name: populate /etc/environment.tags
    lineinfile:
      path: /etc/environment.tags
      regexp: '^{{ item.key | upper }}=.*'
      line: '{{ item.key | upper }}={{ item.value }}'
    with_dict: {{ et2_tags.tags }}
