---

- name: copy check_mem
  copy: src=check_mem dest=/usr/local/bin/check_mem mode=755

- name: copy consul memory check definition
  copy:
    src="memory.check.json"
    dest="/etc/consul/agent/memory.check.json"
  notify:
    - reload consul

- name: copy consul disk check definition
  copy:
    src="disk.check.json"
    dest="/etc/consul/agent/disk.check.json"
  notify:
    - reload consul

- name: copy consul load check defininiot
  copy:
    src="load.check.json"
    dest="/etc/consul/agent/load.check.json"
  notify:
    - reload consul
