---

  - name: copy mongodb from s3
    s3:
      bucket="sugarush-us-west-2-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      mode="get"
      dest="/tmp/mongodb.pkg.tar.xz"
      object="/mongodb-{{ mongodb_version }}-x86_64.pkg.tar.xz"

  - name: copy boost from s3
    s3:
      bucket="sugarush-us-west-2-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      mode="get"
      dest="/tmp/boost.pkg.tar.xz"
      object="/boost-{{ boost_version }}-x86_64.pkg.tar.xz"

  - name: copy boost libs from s3
    s3:
      bucket="sugarush-us-west-2-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      mode="get"
      dest="/tmp/boost-libs.pkg.tar.xz"
      object="/boost-libs-{{ boost_version }}-x86_64.pkg.tar.xz"

  - name: install mongodb
    command: pacman --noconfirm -U /tmp/mongodb.pkg.tar.xz /tmp/boost.pkg.tar.xz /tmp/boost-libs.pkg.tar.xz

  - name: create mongodb.service.d
    file:
      state="directory"
      path="/etc/systemd/system/mongodb.service.d"

  - name: copy 00-limits.conf to mongodb.service.d
    copy:
      src="00-limits.conf"
      dest="/etc/systemd/system/mongodb.service.d/00-limits.conf"

  - name: copy 00-hugepage.conf to tmpfiles.d
    copy:
      src="00-hugepage.conf"
      dest="/etc/tmpfiles.d/00-hugepage.conf"

  - name: template mongodb.conf
    template:
      src="mongodb.conf.tpl"
      dest="/etc/mongodb.conf"

  - name: copy mongodb consul service definition
    template:
      src="mongodb.service.json.tpl"
      dest="/etc/consul/agent/mongodb.service.json"
    notify:
      - reload consul
