---

  - name: copy mongodb from s3
    s3:
      bucket="sugarush-us-west-2-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      mode="get"
      dest="/tmp/mongodb.pkg.tar.xz"
      object="/mongodb-3.2.9-2-x86_64.pkg.tar.xz"

  - name: install mongodb
    command: pacman --noconfirm -U /tmp/mongodb.pkg.tar.xz

  - name: template mongodb.conf
    template:
      src="mongodb.conf.tpl"
      dest="/etc/mongodb.conf"

  - name: copy mongodb consul service definition
    template:
      src="mongodb.service.json.tpl"
      dest="/etc/consul/consul.d/client/mongodb.service.json"
    notify:
      - reload consul@client
