---

#  - name: copy mongodb from s3
#    s3:
#      bucket="sugarush-us-west-2-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
#      object="/mongodb-{{ mongodb_version }}-x86_64.pkg.tar.xz"
#      dest="/tmp/mongodb.pkg.tar.xz"
#      mode="get"
#
#  - name: copy boost from s3
#    s3:
#      bucket="sugarush-us-west-2-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
#      object="/boost-{{ boost_version }}-x86_64.pkg.tar.xz"
#      dest="/tmp/boost.pkg.tar.xz"
#      mode="get"
#
#  - name: copy boost libs from s3
#    s3:
#      bucket="sugarush-us-west-2-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
#      object="/boost-libs-{{ boost_version }}-x86_64.pkg.tar.xz"
#      dest="/tmp/boost-libs.pkg.tar.xz"
#      mode="get"
#
#  - name: copy wiredtiger libs from s3
#    s3:
#      bucket="sugarush-us-west-2-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
#      object="/wiredtiger-{{ wiredtiger_version }}-x86_64.pkg.tar.xz"
#      dest="/tmp/wiredtiger.pkg.tar.xz"
#      mode="get"
#
#  - name: install mongodb
#    command: pacman --noconfirm -U /tmp/mongodb.pkg.tar.xz /tmp/boost.pkg.tar.xz #/tmp/boost-libs.pkg.tar.xz /tmp/wiredtiger.pkg.tar.xz

  - name: install mongodb
    pacman:
      name="mongodb"
      state="present"
      update_cache="yes"

  - name: create /data directory
    file:
      path: "{{ data_dir }}"
      state: directory
      owner: mongodb
      mode: 0700

  - name: check for /dev/xvdb xfs file system
    command: /usr/bin/blkid /dev/xvdb -s TYPE -o value
    register: file_system
    ignore_errors: yes

  - name: create xfs file system for /dev/xvdb
    command: /usr/bin/mkfs.xfs -L data /dev/xvdb
    when: file_system.stdout != "xfs"

  - name: create fstab entry for /dev/xvdb
    lineinfile:
      dest: /etc/fstab
      regexp: "^LABEL=data.*"
      line: "LABEL=data {{ data_dir }} xfs nobarrier,noatime 0 0"

  - name: mount data volume (/dev/xvdb) to /data
    command: /usr/bin/mount LABEL=data
    ignore_errors: yes

  - name: write hugepage drop-in
    shell: echo "{{ hugepage }}" > {{ tmpfiles }}/00-hugepage.conf
    notify:
      - daemon-reload
