---

  - name: make sure consul client is available
    wait_for:
      host="{{ lookup('env', 'HOSTNAME') }}"
      port="8400"
      timeout="30"
    ignore_errors: yes

  - name: get consul kv accesskey
    consul_get:
      key="ansible/{{ lookup('env', 'ROLE') }}/access-key"
      host="{{ lookup('env', 'HOSTNAME') }}"
    register: access_key
    ignore_errors: yes

  - name: get consul kv secretkey
    consul_get:
      key="ansible/{{ lookup('env', 'ROLE') }}/secret-key"
      host="{{ lookup('env', 'HOSTNAME') }}"
    register: secret_key
    ignore_errors: yes

  - name: get consul kv region
    consul_get:
      key="ansible/{{ lookup('env', 'ROLE') }}/region"
      host="{{ lookup('env', 'HOSTNAME') }}"
    register: region
    ignore_errors: yes

  - name: get consul kv bucket
    consul_get:
      key="ansible/{{ lookup('env', 'ROLE') }}/bucket"
      host="{{ lookup('env', 'HOSTNAME') }}"
    register: bucket
    ignore_errors: yes

  - name: template registry service
    template:
      src="registry.service.tpl"
      dest="/etc/systemd/system/registry.service"
      mode="0600"
    notify:
      - daemon-reload
    ignore_errors: yes

  - name: copy consul config
    copy:
      src="registry.json"
      dest="/etc/consul/consul.d/client/registry.json"
    notify:
      - reload consul@client

  - name: enable registry
    service:
      name="registry"
      enabled="yes"
      state="started"
