---

  - hosts: localhost
    connection: local

    pre_tasks:

      - name: update pacman cache
        pacman: update_cache=yes
        tags: [ "configure" ]

    roles:

      # include systemd handlers first (i.e. daemon-reload)
      - { role: systemd, tags: [ "systemd" ] }

      # meta roles
      - { role: admin, tags: [ "admin" ] }
      - { role: build, tags: [ "build" ] }
      - { role: control, tags: [ "control" ] }
      - { role: database, tags: [ "database" ] }
      - { role: fleet, tags: [ "fleet" ] }
      - { role: hub, tags: [ "hub" ] }
      - { role: monitor, tags: [ "monitor" ] }
      - { role: proxy, tags: [ "proxy" ] }
      - { role: swarm, tags: [ "swarm" ] }

    post_tasks:

      - name: restart unbound
        command: systemctl restart unbound
        tags: [ "configure" ]

      - name: restart systemd-resolved
        command: systemctl restart systemd-resolved
        tags: [ "configure" ]
