---

  - hosts: localhost
    connection: local

    pre_tasks:

      - name: update pacman cache
        pacman: update_cache=yes

    roles:

      # include the daemon-reload handler first
      #- { role: systemd, tags: [ "systemd" ] }

      # meta roles
      - { role: admin, tags: [ "admin" ] }
      - { role: build, tags: [ "build" ] }
      - { role: control, tags: [ "control" ] }
      - { role: database, tags: [ "database" ] }
      - { role: fleet, tags: [ "fleet" ] }
      - { role: hub, tags: [ "hub" ] }
      - { role: monitor, tags: [ "monitor" ] }
      - { role: proxy, tags: [ "proxy" ] }
      - { role: swarm, tags: [ "swarm" ] }
