---

  - name: install unbound
    pacman: name=unbound state=present

  - name: template config
    template: src=unbound.conf.j2 dest=/etc/unbound/unbound.conf
    notify:
      - reload unbound

  - name: create /etc/systemd/system/unbound.service.d
    file:
      path="/etc/systemd/system/unbound.service.d"
      state="directory"

  - name: copy 00-before-systemd-networkd.conf
    copy:
      src="00-before-systemd-networkd.conf"
      dest="/etc/systemd/system/unbound.service.d/00-before-systemd-networkd.conf"
    notify:
      - daemon-reload
      - restart unbound
      - restart systemd-networkd

  - name: systemctl daemon-reload
    command: systemctl daemon-reload

  - name: enable and start unbound
    service: name=unbound enabled=yes state=started

  - name: copy consul config
    copy: src=unbound.check.json dest=/etc/consul/consul.d/client/unbound.check.json
    notify:
      - reload consul@client
      - reload consul@server
