---

  - name: install unbound
    pacman: name=unbound state=present

  - name: template config
    template: src=unbound.conf.j2 dest=/etc/unbound/unbound.conf
    notify:
      - reload unbound

  - name: enable and start unbound
    service: name=unbound enabled=yes state=started

  - name: copy consul config
    copy: src=unbound.json dest=/etc/consul/consul.d/client/unbound.json
    notify:
      - reload consul@client
      - reload consul@server
