---

  - name: install unbound
    pacman:
      name="unbound"
      state="present"
    notify:
      - start unbound

  - name: template config
    template:
      src="unbound.conf.j2"
      dest="/etc/unbound/unbound.conf"
    notify:
      - reload unbound

  - name: create /etc/systemd/system/unbound.service.d
    file:
      path="/etc/systemd/system/unbound.service.d"
      state="directory"

  - name: create /etc/systemd/system/systemd-resolved.service.d
    file:
      dest="/etc/systemd/system/systemd-resolved.service.d"
      state="directory"

  - name: copy 00-unit.conf
    copy:
      dest="/etc/systemd/system/unbound.service.d/00-unit.conf"
      src="unbound.service.d/00-unit.conf"
    notify:
      - daemon-reload
      - restart unbound

  - name: copy 00-unit.conf
    copy:
      dest="/etc/systemd/system/systemd-resolved.service.d/00-unit.conf"
      src="systemd-resolved.service.d/00-unit.conf"
    notify:
      - daemon-reload
      - restart unbound

  - name: copy consul config
    copy:
      src="unbound.check.json"
      dest="/etc/consul/consul.d/{{ meta | replace('consul-', '') }}/unbound.check.json"
    notify:
      - reload consul@client
      - reload consul@server
