- name: install aws-cli
  pacman:
    name="aws-cli"
    state="present"

- name: add consul members command to .zshrc
  lineinfile:
    create="yes"
    dest="{{ lookup('env', 'HOME') }}/.zshrc"
    line="alias consul members=\"consul members --rpc-addr $HOSTNAME:8400 | grep -V Node | sort -h\""
