---

  - name: copy telegraf from s3
    s3:
      bucket="{{ lookup('env', 'IDENTIFIER') }}-{{ lookup('env', 'REGION') }}-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      mode="get"
      dest="/tmp/telegraf.pkg.tar.xz"
      object="/telegraf-1.0.1-1-x86_64.pkg.tar.xz"

  - name: install telegraf
    command: pacman --noconfirm -U /tmp/telegraf.pkg.tar.xz

  - name: template telegraf.conf to /etc/telegraf
    template:
      src="telegraf.conf.tpl"
      dest="/etc/telegraf/telegraf.conf"
      owner="telegraf"
      group="telegraf"
      mode="0770"

  - name: start and enable telegraf
    command: systemctl enable --now telegraf

  - name: copy influxdb-telegraf consul check
    copy:
      src="influxdb-telegraf.check.json"
      dest="/etc/consul/consul.d/client/influxdb-telegraf.check.json"
    notify:
      - reload consul@client
      - reload consul@server
