---

  - name: copy telegraf from s3
    s3:
      bucket="{{ lookup('env', 'IDENTIFIER') }}-{{ lookup('env', 'REGION') }}-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      object="/telegraf-{{ package_version }}-x86_64.pkg.tar.xz"
      dest="/tmp/telegraf.pkg.tar.xz"
      mode="get"

  - name: install telegraf
    command: pacman --noconfirm -U /tmp/telegraf.pkg.tar.xz

  - name: template telegraf.conf to /etc/telegraf
    template:
      src="telegraf.conf.tpl"
      dest="/etc/telegraf/telegraf.conf"
      owner="telegraf"
      group="telegraf"
      mode="0770"
    notify:
      - enable influxdb-telegraf
      - restart influxdb-telegraf

  - name: copy influxdb-telegraf consul check
    copy:
      src="influxdb-telegraf.check.json"
      dest="/etc/consul/agent/influxdb-telegraf.check.json"
    notify:
      - reload consul
