dependencies:

  - { role: base, meta: admin }
  - { role: consul-client, meta: admin }
  - { role: influxdb-chronograf, meta: admin }
  - { role: influxdb-kapacitor, meta: admin }
  - { role: swarm-ui, meta: admin }
  - { role: systemd-logentries, meta: admin }
