---

  - name: create data directories
    file:
      path: "{{ data_dir }}/{{ item }}"
      state: directory
      owner: mongodb
      mode: 0700
    with_items: "{{ data_dirs }}"

  - name: template service file
    template:
      src: mongodb-{{ item }}.service.tpl
      dest: "{{ system }}/mongodb-{{ item }}.service"
    with_items: "{{ templates }}"
    notify:
      - daemon-reload

  - name: create service drop-in
    file:
      path: "{{ system }}/mongodb-{{ item }}.service.d"
      state: directory
    with_items: "{{ templates }}"

  - name: write limits drop-in
    shell: echo "{{ limits }}" > {{ system }}/mongodb-{{ item }}.service.d/00-limits.conf
    with_items: "{{ templates }}"
    notify:
      - daemon-reload

  - name: template mongodb consul service definition
    template:
      src: mongodb-{{ item }}.service.json.tpl
      dest: /etc/consul/agent/mongodb-{{ item }}.service.json
    with_items: "{{ templates }}"
    notify:
      - reload consul
