- pacman:
    name="python2-netifaces"
    state="present"

- pacman:
    name="libmicrohttpd"
    state="present"

- copy:
    dest="/usr/local/bin/environment.py"
    src="environment.py"
    mode="0700"

- copy:
    dest="/etc/systemd/system/environment.service"
    src="system/environment.service"

- file:
    dest="/etc/systemd/journald.conf.d"
    state="directory"

- copy:
    dest="/etc/systemd/journald.conf.d/00-persistent.conf"
    src="journald.conf.d/00-persistent.conf"

- file:
    dest="/etc/systemd/system/systemd-journal-gatewayd.socket.d"
    state="directory"

- copy:
    dest="/etc/systemd/system/systemd-journal-gatewayd.socket.d/00-socket.conf"
    src="system/systemd-journal-gatewayd.socket.d/00-socket.conf"

- file:
    dest="/etc/systemd/network/{{ item }}.network"
    state="touch"
  with_items:
    "{{ interfaces }}"

- lineinfile:
    dest="/etc/systemd/network/{{ item }}.network"
    line="UseDomains=yes"
    state="present"
  with_items:
    "{{ interfaces }}"
  notify:
    - restart systemd-resolved

- command: systemctl enable --now systemd-journal-gatewayd.socket

- copy:
    dest="/etc/systemd/system/ansible.{{ item }}"
    src="system/ansible.{{ item }}"
  with_items:
    - service
    - timer
  notify:
    - start ansible.timer
