---

  - name: copy influxdb-relay from s3
    s3:
      bucket="{{ lookup('env', 'IDENTIFIER') }}-{{ lookup('env', 'REGION') }}-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      object="/influxdb-relay-{{ package_version }}-x86_64.pkg.tar.xz"
      dest="/tmp/influxdb-relay.pkg.tar.xz"
      mode="get"

  - name: install influxdb-relay
    command: pacman --noconfirm -U /tmp/influxdb-relay.pkg.tar.xz

  - name: add user consul to group influxdb
    user:
      append="yes"
      name="consul"
      groups="influxdb"

  - name: set permissions on /etc/influxdb-relay
    file:
      path="/etc/influxdb-relay/config"
      state="directory"
      owner="influxdb"
      group="influxdb"
      mode="0770"

  - name: copy influxdb-relay consul-template config
    copy:
      src="influxdb-relay.toml"
      dest="/etc/consul-template/config/influxdb-relay.toml"
    notify:
      - enable consul-template@influxdb-relay
      - reload consul-template@influxdb-relay

  - name: copy influxdb-relay systemd service
    copy:
      src="influxdb-relay.service"
      dest="/etc/systemd/system/influxdb-relay.service"
    notify:
      - daemon-reload
      - enable influxdb-relay
      - restart influxdb-relay

  - name: template influxdb-relay consul-template template
    template:
      src="influxdb-relay.toml.tpl"
      dest="/etc/consul-template/template/influxdb-relay.toml"
    notify:
      - reload consul-template@influxdb-relay

  - name: template influxdb-relay http and udp consul service files
    template:
      src="influxdb-relay-{{ item }}.service.json.tpl"
      dest="/etc/consul/agent/influxdb-relay-{{ item }}.service.json"
    items:
      - http
      # - udp
    notify:
      - reload consul
