---

  dependencies:

    - { role: "consul", meta: "consul-client"}
    - { role: "unbound", meta: "consul-client" }
    - { role: "docker", meta: "consul-client" }

    - { role: "consul-template", meta: "consul-server" }
