---

  - name: copy influxdb from s3
    s3:
      bucket="{{ lookup('env', 'IDENTIFIER') }}-{{ lookup('env', 'REGION') }}-{{ lookup('env', 'DEPLOY') }}-archlinux-repository"
      mode="get"
      dest="/tmp/influxdb.pkg.tar.xz"
      object="/influxdb-1.0.2-2-x86_64.pkg.tar.xz"

  - name: install influxdb
    command: pacman --noconfirm -U /tmp/influxdb.pkg.tar.xz

  - name: template influxdb config
    template:
      src="influxdb.conf.tpl"
      dest="/etc/influxdb/influxdb.conf"
    notify:
      - daemon-reload
      - restart influxdb

  - name: enable and start influxdb
    command: systemctl enable --now influxdb

  - name: wait until influxdb has started
    wait_for:
      delay="5"
      port="8085"

  - name: create influxdb telegraf database
    command: influx -host {{ lookup('env', 'HOST_IP') }} -port 8085 -execute "create database telegraf"

  - name: template influxdb consul service
    template:
      src="influxdb-{{ item }}.service.json.tpl"
      dest="/etc/consul/consul.d/client/influxdb-{{ item }}.service.json"
    items:
      - admin
      - http
      # - udp
    notify:
      - daemon-reload
      - reload consul@client
      - reload consul@server
