---

  - name: copy swarm-ui systemd service file
    template:
      src="swarm-ui.service.tpl"
      dest="/etc/systmed/system/swarm-ui.service"
    notify:
      - daemon-reload
      - restart swarm-ui

  - name: enable and start swarm-ui
    command: systemctl enable --now swarm-ui
