- name: start configure.timer
  command: systemctl enable --now configure.timer

- name: restart environment
  command: systemctl restart environment.service

- name: restart systemd-networkd
  command: systemctl restart systemd-networkd
  notify:
    - restart environment

- name: daemon-reload
  command: systemctl daemon-reload
