---

  - name: template mongo-cayley systemd service file
    template:
      src="mongo-cayley.service.tpl"
      dest="/etc/systemd/system/mongo-cayley.service"
    notify:
      - daemon-reload
      - enable mongo-cayley
      - start mongo-cayley

  - name: template mongodb-cayley consul service file
    template:
      src="mongo-cayley.service.json.tpl"
      dest="/etc/consul/agent/mongo-cayley.service.json"
    notify:
      - reload consul
