---

  - name: copy consul-alerts service file
    copy:
      dest="/etc/systemd/system/consul-alerts.service"
      src="consul-alerts.service"
    notify:
      - daemon-reload
      - restart consul-alerts

  - name: copy consul config
    copy:
      dest="/etc/consul/agent/consul-alerts.check.json"
      src="consul-alerts.check.json"
    notify:
      - reload consul
