# display a sorted list of consul nodes
alias members="consul members --rpc-addr $HOSTNAME:8400 | grep -v Node | sort -h"

# run docker commands agains swarm managers
alias swarm="docker -H tcp://swarm-manager.service.consul:4000"

# run commands on remote nodes
ansible-cmd() {
  ansible -i /root/ansible/inventory.py "tag_${1}_${2}_${DEPLOY}" -m command -a "${3}"
}

# the command to restart the ansible configure systemd service
RESTART_CONFIGURE_COMMAND="systemctl restart configure"

# restart the configure systemd service on a subset of nodes
ansible-configure() {
  ansible-cmd "Name" "${1}" "${RESTART_CONFIGURE_COMMAND}"
}

# restart the configure systemd service on all nodes
ansible-configure-all() {
  ansible-cmd "Managed" "terraform" "${RESTART_CONFIGURE_COMMAND}"
}

# run a command on a remote node using ansible-cmd results
ansible-ssh() {
  IP_ADDR=$(grep -oE "^([0-9]{1,3}\.){3}[0-9]{1,3}" | sed -n "1p")
  ssh ${IP_ADDR} "${1}"
}

# tail the journal of a service on a remote node using ansible-cmd results
ansible-journal() {
  ansible-ssh "journalctl -fu ${1}"
}
