template {
  command = "systemctl restart influxdb-relay"

  source = "/etc/consul-template/template/influxdb-relay.toml"
  destination = "/etc/influxdb-relay/influxdb-relay.toml"

  left_delimiter  = "<<"
  right_delimiter = ">>"
}
