---
  dependencies:

    - { role: consul-client, meta: swarm }

    - { role: "influxdb-telegraf", meta: "control" }
    - { role: "flannel", meta: "control" }
    - { role: "swarm-agent", meta: "control" }
  #  - { role: systemd-logentries, meta: swarm }
