---

  - name: install go and godep
    command: pacman --noconfirm -S go godep

  - name: create golang group
    group:
      name="golang"

  - name: create /usr/local/go
    file:
      dest="/usr/local/go"
      state="directory"
      group="golang"
      mode="0775"

  - name: add GOPATH to /etc/environment
    lineinfile:
      dest="/etc/environment"
      regexp="^GOPATH="
      line="GOPATH=/usr/local/go"
