dependencies:

  - { role: "consul-server", meta: "control" }
#  - { role: consul-backup, meta: control }
#  - { role: consul-template, meta: control }
#  - { role: consul-ui, meta: control }
#  - { role: etcd, meta: control }
#  - { role: influxdb, meta: control }
#  - { role: influxdb-relay, meta: control }
#  - { role: swarm-manager, meta: control }
